name: continue-integration(CI)

on:
  push:
    branches:
      - dev-branch
      - master


jobs:
  build: 
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Deploying the image
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'inventory-fr' }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME